apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: blog
# build:
#   artifacts:
#     - image: blog
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
profiles:
  - name: dev
    build:
      local:
        push: false
      artifacts:
        - image: hnmishra/client  
          context: client
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: "src/**/*.js"
                dest: .
        - image: hnmishra/comments  
          context: comments
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: "*.js"
                dest: .
        - image: hnmishra/event-bus  
          context: event-bus
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: "*.js"
                dest: .
        - image: hnmishra/moderation
          context: moderation
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: "*.js"
                dest: .
        - image: hnmishra/posts
          context: posts
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: "*.js"
                dest: .
        - image: hnmishra/query
          context: query
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: "*.js"
                dest: .
